### ISSUE TITLE
Cypress test failing

### ISSUE THREAD

**Issue by weelillad** [kentcdodds/cypress-testing-workshop#1]
`npm run setup` does not complete because one of the cypress tests consistently fails. I narrowed it down to this line: https://github.com/kentcdodds/cypress-testing-workshop/blob/a9b1ece2ed07e8fce5da9b9cc5bf36820593d4ea/cypress-final/e2e/02.js#L10

When running the application and examining the DOM, I see that my calculator digit keys class is `calculator_digitKeys__2wKR5` instead of `calculator_digitKeys__ILLGP` as the test expected.

Error message excerpt:

```shell
  Running: 02.js...                                                 (3 of 12) 


  anonymous calculator
    ✓ has the right title (265ms)
    1) can make calculations


  1 passing (5s)
  1 failing

  1) anonymous calculator can make calculations:
     CypressError: Timed out retrying: Expected to find element: '.calculator_digitKeys__ILLGP > :nth-child(3)', but never found it.
      at Object.cypressErr (http://localhost:3000/__cypress/runner/cypress_runner.js:65727:11)
      at Object.throwErr (http://localhost:3000/__cypress/runner/cypress_runner.js:65692:18)
      at Object.throwErrByPath (http://localhost:3000/__cypress/runner/cypress_runner.js:65719:17)
      at retry (http://localhost:3000/__cypress/runner/cypress_runner.js:59237:16)
      at http://localhost:3000/__cypress/runner/cypress_runner.js:51312:18
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:131273:23)
      at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:129291:31)
      at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:129348:18)
      at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:129393:10)
      at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:129468:18)
      at Async._drainQueue (http://localhost:3000/__cypress/runner/cypress_runner.js:126197:16)
      at Async._drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:126207:10)
      at Async.drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:126081:14)
      at <anonymous>




  (Results)

  ┌─────────────────────────┐
  │ Tests:        2         │
  │ Passing:      1         │
  │ Failing:      1         │
  │ Pending:      0         │
  │ Skipped:      0         │
  │ Screenshots:  1         │
  │ Video:        true      │
  │ Duration:     4 seconds │
  │ Spec Ran:     02.js     │
  └─────────────────────────┘
```

All other tests pass.

**Comment by kentcdodds** [comment]
Ah, rats. In the workshop we'll talk about why this is happening and how to
avoid it, but I need to have the example here for the instruction 😅

I'll get that fixed after dinner. Thank you! And sorry for the trouble.

**Comment by weelillad** [comment]
That's really interesting, I'm looking forward even more to the workshop now :grin:

**Comment by kentcdodds** [comment]
Ok, it's been fixed. You should be good to just do:

```
git pull
npm run validate
```
